Revert "error CS1503: Argument 2: cannot convert from 'System.Collections.Generic.IEnumerable<object>' to 'System.Collections.Generic.IEnumerable<string>'"
This reverts commit 0fa5bba964a5b58b191cba0a0de2271dc04f5207.