Revert "Resolve error CS0019: Operator '!=' cannot be applied to operands of type 'KeyValuePair<dynamic, dynamic>' and '<null>'"
This reverts commit 5bcee0fdff6ec224ac551d693d93d7b928a33239.